apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  labels:
    app: podinfo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podinfo
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
      - image: noimage:latest
        name: podinfo
        serviceAccountName: podinfo
        ports:
        - containerPort: 9898
          name: http
        envFrom:
        - configMapRef:
            name: podinfo-config
